### ISSUE TITLE
Missing media types for MyAnimeList causes crash

### ISSUE THREAD

**Issue by imawizrd** [z411/trackma#747]
The tool is currently missing some media types for MyAnimeList, causing the tool to crash when parsing information.

To reproduce this, add some anime to the watching list as an example. Say one that has a "cm" type, which stands for "commercial". 

Open trackma and switch to the list where the anime is and try to get the information.

Say the anime list entry is index 10 in this list and you do `info 10`. 

Then the crash happens with an error like this one:

````
[mal] (anime) watching >> info 10
Traceback (most recent call last):
  File "./.venv/lib/python3.11/site-packages/trackma/data.py", line 440, in info_get
    return self.infocache[showid]
           ~~~~~~~~~~~~~~^^^^^^^^
KeyError: 40799

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./.venv/bin/trackma", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "./.venv/lib/python3.11/site-packages/trackma/ui/cli.py", line 1081, in main
    main_cmd.cmdloop()
  File "/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
           ^^^^^^^^^^^^^^^^^
  File "./.venv/lib/python3.11/site-packages/trackma/ui/cli.py", line 777, in onecmd
    return self.execute(cmd, args, line)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./.venv/lib/python3.11/site-packages/trackma/ui/cli.py", line 794, in execute
    return func(args)
           ^^^^^^^^^^
  File "./.venv/lib/python3.11/site-packages/trackma/ui/cli.py", line 374, in do_info
    details = self.engine.get_show_details(show)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./.venv/lib/python3.11/site-packages/trackma/engine.py", line 451, in get_show_details
    return self.data_handler.info_get(show)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./.venv/lib/python3.11/site-packages/trackma/data.py", line 442, in info_get
    return self.api.request_info([show])[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./.venv/lib/python3.11/site-packages/trackma/lib/libmal.py", line 346, in request_info
    infolist.append(self._parse_info(data))
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "./.venv/lib/python3.11/site-packages/trackma/lib/libmal.py", line 380, in _parse_info
    'type': self.type_translate[item['media_type']],
            ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'cm'

````

I created a patch file with some missing types as a workaround. Apply with `patch -p0 < file.patch` next to the `.venv` folder:

````patch
--- .venv/lib/python3.11/site-packages/trackma/lib/libmal.py	XXXX-XX-XX xx:xx:xx
+++ ~/Documents/libmal-fix.py	XXXX-XX-XX xx:xx:xx
@@ -105,6 +105,8 @@
         'manhua': utils.Type.MANGA,
         'one_shot': utils.Type.ONE_SHOT,
         'doujinshi': utils.Type.MANGA,
+        'cm': utils.Type.COMMERCIAL,
+        'pv': utils.Type.PROMOTIONAL,
     }
     
     status_translate = {
--- .venv/lib/python3.11/site-packages/trackma/utils.py	XXXX-XX-XX xx:xx:xx
+++ ~/Documents/utils-fix.py	XXXX-XX-XX xx:xx:xx
@@ -120,6 +120,8 @@
     MOVIE = "Movie"
     OVA = "OVA"
     SPECIAL = "Special"
+    COMMERCIAL = "Commercial"
+    PROMOTIONAL = "Promotional"
 
     # manga
     MANGA = "Manga"
--- .venv/lib/python3.11/site-packages/trackma/lib/libmal.py	XXXX-XX-XX xx:xx:xx
+++ ~/Documents/libmal-fix.py	XXXX-XX-XX xx:xx:xx
@@ -107,6 +107,7 @@
         'doujinshi': utils.Type.MANGA,
         'cm': utils.Type.COMMERCIAL,
         'pv': utils.Type.PROMOTIONAL,
+        'tv_special': utils.Type.TV_SPECIAL,
     }
     
     status_translate = {
--- .venv/lib/python3.11/site-packages/trackma/utils.py	XXXX-XX-XX xx:xx:xx
+++ ~/Documents/utils-fix.py	XXXX-XX-XX xx:xx:xx
@@ -122,6 +122,7 @@
     SPECIAL = "Special"
     COMMERCIAL = "Commercial"
     PROMOTIONAL = "Promotional"
+    TV_SPECIAL = "TV Special"
 
     # manga
     MANGA = "Manga"

````
One note of warning about this patch: after applying this patch and browsing the information, trackma will save these new values to its databases  (`~/.local/share/trackma/<account>`) making this account incompatible with the unpatched trackma version. Make backups of your account data before using this patch.

The patch was tested with version 0.8.6.

**Comment by wise720** [comment]
was fixed in #724 but your solution probably would have been nicer

**Comment by imawizrd** [comment]
Thanks for your solution! I see that your PR fixes a bunch of types in libmal, but the "PV" type is still missing.

I think we can use both solutions. To avoid making changes that would break older versions of the software we can use your solution for the current version which maps to other known types. We can use my solution, which adds new display values for clarity, for a future version that might have breaking changes. This way, we can avoid breaking changes and ensure that new future versions of the database will work with older versions of trackma. Everyone wins! :)

**Comment by wise720** [comment]
@imawizrd  right my bad i had implemented a fallback in #733 (probably had your pv type) but a more descriptive solution would be better. do you just want to make a pull request and next time a maintainer looks over it prob gets merged

**Comment by imawizrd** [comment]
I believe I can close this issue since it’s been addressed. The PRs were merged a year ago so it should be released soon to resolve the catastrophic crash. For others, you can avoid the build process by creating a patch file as I did. Or compose a patch with the code from the PRs by @wise720 if you want to avoid breaking changes.
