### ISSUE TITLE
Anilist seemingly adds show without status

### ISSUE THREAD

**Issue by ToostInc** [z411/trackma#90]
When adding a series through 'Add/Search Shows' it doesn't seem to set a particular status, making it unreachable from the Trackma-client itself. 

This seems to be the default behaviour for Anilist, as adding a series from the site has the same effect, relying on the user to set a status, and otherwise just creating an empty entry (the fact that you can afterwards delete it without error is the only indication that it actually exists).  

This makes sense for the site, should you forget to edit the show initially, you can easily look it up, but for Trackma it might be an idea to set a status automatically, maybe watching or plan to watch, based on whether to show has started airing yet?  
On the rare occasion that you'd add a dropped, on-hold or already completed series, you can then easily edit the entry manually.

**Comment by z411** [comment]
I couldn't test the issue since the server is returning a 500 error when adding or updating for some reason. It might be my mistake, but it isn't telling me what's wrong.

**Comment by z411** [comment]
Should be fixed.

**Comment by ToostInc** [comment]
Seems to be working for me as well, thanks a lot!

**Comment by SleepyMan** [comment]
I just used anichart to add shows from the past 2 seasons and the next season as well. The problem is that for some shows, the "my_progress" is returning a NoneType, not a number as the UI expects. I believe that it's the same problem as this, but the fix only works when adding from trackma itself, not from AniChart/AniList.

If added/updated from the site, it breaks the UI. GTK doesn't respond when clicking on the tray icon, and in Qt lists/menu/etc stays grey (can't interact with the app).

Shouldn't a sane default value be used even when not adding/updating from trackma for interoperability with AniList?

**Comment by z411** [comment]
Sorry I didn't realize the API returned None values since I have all my shows with progress. Let me check.

**Comment by z411** [comment]
Okay, fixed in commit c26988aa47055b2f5f60e68d874dda15b358a31b . Try re-retrieving the list with the CLI (`retrieve` command) and tell me how it goes.

**Comment by SleepyMan** [comment]
It still throws the same exception. Sorry, here's the exception.

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/trackma/ui/qtui.py", line 788, in r_engine_loaded
    self._rebuild_lists(showlist, altnames)
  File "/usr/lib/python2.7/site-packages/trackma/ui/qtui.py", line 373, in _rebuild_lists
    self._rebuild_list(status, filtered_list[status], altnames)
  File "/usr/lib/python2.7/site-packages/trackma/ui/qtui.py", line 397, in _rebuild_list
    self._update_row( widget, i, show, altnames.get(show['id']) )
  File "/usr/lib/python2.7/site-packages/trackma/ui/qtui.py", line 417, in _update_row
    progress_str = "%d / %d" % (show['my_progress'], show['total'])
TypeError: %d format: a number is required, not NoneType

I quickly glanced at it, and assumed it was "my_progress", but it might have been both "my_progress" and "total".

**Comment by z411** [comment]
Did you try re-retrieving the list with the CLI or curses interface first?

**Comment by SleepyMan** [comment]
Yes, I did. Unless the command "retrieve" does not do what it says it does.

**Comment by z411** [comment]
Mhm, weird I can't reproduce it at all now...

**Comment by SleepyMan** [comment]
Hm... anime.info and anime.list is still not json... should I send anything to you to debug it?

**Comment by z411** [comment]
Oh wait, it might be the total, not the progress. Did the same for the total just in case (commit c8b0ab574882d1876ccc4af012f5483c98f7c504)

**Comment by SleepyMan** [comment]
Yes, I also glanced at it quickly, and assumed it was my_progress.
It's working now.

**Comment by z411** [comment]
Great. Will be closing this then.
